# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
    mailchimp_api_key: <%= ENV['MAILCHIMP_API_KEY'] %>
    mailchimp_list_id: <%= ENV['MAILCHIMP_LIST_ID'] %>
    secret_key_base: e2ae141d3ab3bc8ed7cb7f4bf6cb9792a9e91c4da83b0d34a2886567a98b97427a18e1545f67230708d7431a5f7e6e5685c7ffe83376c56487998f3733b5aac1

test:
  secret_key_base: 093bd7980f1a8425c7ea5f82564e81c167ee720527db9c94e172f6c6ec02d054dcc2a96e53c1621d09eaa5da3926ee8ca5782a211ec054503c48da4ae5e6d33e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
    mailchimp_api_key: <%= ENV['MAILCHIMP_API_KEY'] %>
    mailchimp_list_id: <%= ENV['MAILCHIMP_LIST_ID'] %>


    secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
